---
- hosts: k3s_master
  roles:
    - role: k3s
      tags:
        - k3s
        - k3s-master

- hosts: k3s_node
  roles:
    - role: k3s
      tags:
        - k3s
        - k3s-node

- hosts: longhorn_node
  roles:
    - role: longhorn
      tags:
        - longhorn

- hosts: avahi_daemon
  roles:
    - role: avahi-daemon
      tags:
        - avahi
