---
- include_tasks: prereqs/rhel.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: iscsi/rhel.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: nfs/rhel.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: utils/rhel.yml
  when: ansible_os_family == 'RedHat'

- name: Set Node label/annotation to configure longhorn default disk
  kubernetes.core.k8s:
    kubeconfig: "{{ k3s_kubeconfig_file }}"
    state: patched
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: "{{ k3s_node_name }}"
        labels:
          node.longhorn.io/create-default-disk: config
        annotations:
          node.longhorn.io/default-disks-config: "{{ longhorn_default_disks_config | to_json }}"
