---
- include_tasks: prereqs/rhel.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: prereqs/rpios.yml
  when:
    - raspberry_pi | default(false)
    - ansible_os_family == 'Debian'

- set_fact:
    k3s_config_file: "{{ k3s_config_dir }}/config.yaml"

- set_fact:
    k3s_kubeconfig_file: "{{ k3s_config_dir }}/k3s.yaml"

- name: Ensure k3s config directory exists
  file:
    path: "{{ k3s_config_dir }}"
    state: directory
    mode: 0755
  become: true

- name: Download k3s install script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/install_k3s.sh
    mode: 0755

- include_tasks: master.yml
  when: k3s_is_master

- include_tasks: node.yml
  when: not k3s_is_master
