---
- name: Allow k3s apiserver port in firewalld
  ansible.posix.firewalld:
    port: "{{ k3s_https_listen_port }}/tcp"
    state: enabled
    permanent: true
  become: true
  register: k3s_firewalld_apiserver_port

- name: Add k3s Pod network to trusted zone in firewalld
  ansible.posix.firewalld:
    source: "{{ k3s_cluster_cidr }}"
    zone: trusted
    state: enabled
    permanent: true
  become: true
  register: k3s_firewalld_pod_network

- name: Add k3s Service network to trusted zone in firewalld
  ansible.posix.firewalld:
    source: "{{ k3s_service_cidr }}"
    zone: trusted
    state: enabled
    permanent: true
  become: true
  register: k3s_firewalld_service_network

- name: Reload firewalld
  systemd:
    name: firewalld
    state: reloaded
  become: true
  when: k3s_firewalld_apiserver_port.changed or k3s_firewalld_pod_network.changed or k3s_firewalld_service_network.changed
