---
- name: Check for newer cmdline.txt file
  stat:
    path: /boot/firmware/cmdline.txt
  register: new_cmdline_stat_result

- name: Enable cgroups
  lineinfile:
    path: "{{ '/boot/firmware/cmdline.txt' if new_cmdline_stat_result.stat.exists else '/boot/cmdline.txt' }}"
    regexp: '^((?!.*\bcgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  become: true
  register: enable_cgroups

- name: Reboot
  ansible.builtin.reboot:
  become: true
  when: enable_cgroups.changed
