k3s_version: v1.27.1+k3s1
k3s_is_master: true
k3s_node_name: "{{ inventory_hostname }}"
k3s_master_ip: "{{ hostvars[groups['k3s_master'][0]]['ansible_host'] | default(groups['k3s_master'][0]) }}"
k3s_config_dir: /etc/rancher/k3s
k3s_data_dir: /var/lib/rancher/k3s
k3s_disabled_components: []
k3s_disabled_manifests: []
k3s_https_listen_port: 6443
k3s_cluster_cidr: 10.42.0.0/16
k3s_service_cidr: 10.43.0.0/16
